[project]
name = "douban"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "fake-useragent>=2.2.0",
    "matplotlib>=3.10.3",
    "requests>=2.32.4",
    "rich>=14.0.0",
]
